allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
onlyBuiltDependencies:
  - "@cloudflare/workerd-darwin-arm64"
  - "@esbuild/darwin-arm64"
  - "@img/sharp-libvips-darwin-arm64"
  - esbuild
  - sharp
  - workerd
