"use client";
import * as echarts from "echarts";
import { useEffect, useRef, useState } from "react";
import data from "../data/filmTrend.json";
import { EditableInsight } from "./EditableInsight";
import { setBracketAnnotations } from "./chartBrackets";
type QuarterFilter="Q1"|"Q2"|"Q3"|"Q4"|"all";
const colors:Record<string,string>={"网络电影":"#9eb3c9","院线电影 - 其他":"#c8ceca","院线电影上新 TOP 50":"#385577","爱奇艺":"#C0D688","腾讯视频":"#A9BACF","优酷":"#89D8F0","B站":"#EDB795"};
const pct=(a:number,b:number)=>`${a>=b?"+":""}${((a/b-1)*100).toFixed(0)}%`;
function Chart({kind}:{kind:"total"|"coverage"|"platform"}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(!ref.current)return;const chart=echarts.init(ref.current);const common={animationDuration:420,tooltip:{show:false},grid:{left:38,right:18,top:kind==="total"?78:44,bottom:kind==="coverage"?38:64},xAxis:{type:"category",data:data.periods,axisTick:{show:false},axisLine:{lineStyle:{color:"#aeb7b0"}},axisLabel:{color:"#737c76",fontSize:10}},yAxis:{type:"value",...(kind==="coverage"?{min:0,max:50,interval:10}:{}),axisLabel:{color:"#737c76",fontSize:9},splitLine:{lineStyle:{color:"#e4e7e4"}}}};let totals:number[]=[];let series:object[]=[];let legend:object|undefined;
if(kind==="total"){totals=data.periods.map((_,i)=>data.total.series.reduce((s,x)=>s+x.values[i],0));legend={data:data.total.series.map(x=>x.name),bottom:10,itemWidth:9,itemHeight:9,textStyle:{color:"#58615b",fontSize:9}};series=[...data.total.series.map(x=>({name:x.name,type:"bar",stack:"total",data:x.values,barMaxWidth:38,label:{show:true,position:"inside",color:x.name==="院线电影上新 TOP 50"?"#fff":"#263038",fontSize:9,formatter:({value}:{value:number})=>value.toFixed(1)}})),{name:"柱顶合计",type:"bar",data:totals,barMaxWidth:38,barGap:"-100%",silent:true,z:20,itemStyle:{color:"rgba(0,0,0,0)"},label:{show:true,position:"top",distance:8,color:"#161917",fontSize:11,fontWeight:700,formatter:({value}:{value:number})=>value.toFixed(1)}}];}
if(kind==="coverage")series=[{name:"B站有版权",type:"bar",stack:"total",data:data.coverage.covered,barMaxWidth:42,itemStyle:{color:"#385577"},label:{show:true,position:"inside",color:"#fff",fontSize:10,formatter:({value}:{value:number})=>`${value}部\n${value*2}%`}},{name:"其他",type:"bar",stack:"total",data:data.coverage.other,barMaxWidth:42,itemStyle:{color:"#d9dfe8"},label:{show:true,position:"inside",color:"#263038",fontSize:9,formatter:({value}:{value:number})=>`${value}部`}}];
if(kind==="platform"){legend={bottom:10,itemWidth:9,itemHeight:9,textStyle:{color:"#58615b",fontSize:9}};series=data.platform.series.map(x=>({name:x.name,type:"bar",data:x.values,barMaxWidth:17,itemStyle:{color:colors[x.name]},label:{show:true,position:"top",color:"#263038",fontSize:8,formatter:({value}:{value:number})=>value.toFixed(1)}}));}
chart.setOption({...common,legend,series});const draw=()=>kind==="total"&&setBracketAnnotations(chart,[{previousIndex:1,currentIndex:2,previousValue:totals[1],currentValue:totals[2],label:pct(totals[2],totals[1]),level:1,targetGap:26,labelFontSize:8}]);requestAnimationFrame(draw);const ob=new ResizeObserver(()=>{chart.resize();requestAnimationFrame(draw)});ob.observe(ref.current);return()=>{ob.disconnect();chart.dispose()};},[kind]);return <div ref={ref} className="film-chart" role="img" aria-label={kind==="total"?"电影有效播放构成":kind==="coverage"?"B站版权覆盖率":"分平台播放量"}/>}
export function FilmTrend(){const[q,setQ]=useState<QuarterFilter>("Q2");return <section className="horizontal-drama-trend film-trend"><div className="horizontal-drama-lead"><div className="horizontal-drama-subhead"><span>01</span><h4>电影大盘趋势</h4></div><EditableInsight lead="电影播放继续收缩，B站院线新片覆盖提升" body="26Q2 电影有效播放 46.4 亿，同比 -18%；院线电影上新 TOP 50 播放 9.8 亿，同比 -8%。B站覆盖 TOP 50 中的 33 部，覆盖率升至 66%；B站播放 1.1 亿，同比 +10%。" highlights={["46.4 亿","-18%","9.8 亿","-8%","33 部","66%","1.1 亿","+10%"]} storageKey="ogv-market-review:26q2:film-trend-v1"/></div><div className="horizontal-drama-quarter-filter" aria-label="选择季度"><span>显示季度</span>{(["Q1","Q2","Q3","Q4","all"] as const).map(x=><button key={x} type="button" className={q===x?"selected":""} aria-pressed={q===x} onClick={()=>setQ(x)}>{x==="all"?"全部":x}</button>)}</div><div className="film-charts"><article className="horizontal-drama-panel"><header><h5>byQ 电影有效播放（亿）</h5></header><Chart kind="total"/></article><article className="horizontal-drama-panel"><header><div><h5>B站版权覆盖率</h5><span>院线电影上新 TOP 50</span></div></header><Chart kind="coverage"/></article><article className="horizontal-drama-panel"><header><div><h5>分平台播放（亿）</h5><span>院线电影上新 TOP 50</span></div></header><Chart kind="platform"/></article></div><p className="horizontal-drama-source film-source">数据范围：仅院线电影上新 TOP 50；时间范围：2024、2025、2026 年 Q2。数据来源：{data.source}。</p></section>}
