"use client";
import * as echarts from "echarts";
import { useEffect, useRef, useState } from "react";
import data from "../data/filmTrend.json";
import { EditableInsight } from "./EditableInsight";
import { type BracketComparison, setBracketAnnotations } from "./chartBrackets";
import { FilmTop10 } from "./FilmTop10";
type QuarterFilter="Q1"|"Q2"|"Q3"|"Q4"|"all";
const colors:Record<string,string>={"网络电影":"#9eb3c9","院线电影 - 其他":"#d9dfe8","院线电影上新 TOP 50":"#385577","爱奇艺":"#C0D688","腾讯视频":"#A9BACF","优酷":"#89D8F0","B站":"#D99AAF"};
const pct=(a:number,b:number)=>`${a>=b?"+":""}${((a/b-1)*100).toFixed(0)}%`;
function Chart({kind}:{kind:"total"|"coverage"|"platform"}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(!ref.current)return;const chart=echarts.init(ref.current);const common={animationDuration:420,tooltip:{show:false},grid:{left:38,right:kind==="platform"?104:18,top:kind==="total"?78:44,bottom:64},xAxis:{type:"category",data:data.periods,axisTick:{show:false},axisLine:{lineStyle:{color:"#aeb7b0"}},axisLabel:{color:"#737c76",fontSize:10}},yAxis:{type:"value",...(kind==="coverage"?{min:0,max:50,interval:10}:{}),axisLabel:{color:"#737c76",fontSize:9},splitLine:{lineStyle:{color:"#e4e7e4"}}}};let totals:number[]=[];let series:object[]=[];let legend:object|undefined;
if(kind==="total"){totals=data.periods.map((_,i)=>data.total.series.reduce((s,x)=>s+x.values[i],0));legend={data:data.total.series.map(x=>x.name),bottom:10,itemWidth:9,itemHeight:9,textStyle:{color:"#58615b",fontSize:9}};series=[...data.total.series.map(x=>({name:x.name,type:"bar",stack:"total",data:x.values,barMaxWidth:38,itemStyle:{color:colors[x.name]},label:{show:true,position:"inside",color:x.name==="院线电影上新 TOP 50"?"#fff":"#263038",fontSize:9,formatter:({value}:{value:number})=>value.toFixed(1)}})),{name:"柱顶合计",type:"bar",data:totals,barMaxWidth:38,barGap:"-100%",silent:true,z:20,itemStyle:{color:"rgba(0,0,0,0)"},label:{show:true,position:"top",distance:8,color:"#161917",fontSize:11,fontWeight:700,formatter:({value}:{value:number})=>value.toFixed(1)}}];}
if(kind==="coverage"){legend={bottom:10,data:["B站有版权","其他"],itemWidth:9,itemHeight:9,textStyle:{color:"#58615b",fontSize:9}};series=[{name:"B站有版权",type:"bar",stack:"total",data:data.coverage.covered,barMaxWidth:42,itemStyle:{color:"#385577"},label:{show:true,position:"inside",color:"#fff",fontSize:10,formatter:({value}:{value:number})=>`${value}部\n${value*2}%`}},{name:"其他",type:"bar",stack:"total",data:data.coverage.other,barMaxWidth:42,itemStyle:{color:"#d9dfe8"},label:{show:true,position:"inside",color:"#263038",fontSize:9,formatter:({value}:{value:number})=>`${value}部`}}];}
if(kind==="platform"){totals=data.periods.map((_,i)=>data.platform.series.reduce((s,x)=>s+x.values[i],0));series=[...data.platform.series.map(x=>({name:x.name,type:"bar",stack:"total",data:x.values,barMaxWidth:38,itemStyle:{color:colors[x.name]},label:{show:x.name!=="B站",position:"inside",color:x.name==="腾讯视频"?"#fff":"#263038",fontSize:9,formatter:({value,dataIndex}:{value:number,dataIndex:number})=>`${value.toFixed(1)}\n(${(value/totals[dataIndex]*100).toFixed(0)}%)`}})),{name:"柱顶合计",type:"bar",data:totals,barMaxWidth:38,barGap:"-100%",silent:true,z:20,itemStyle:{color:"rgba(0,0,0,0)"},label:{show:true,position:"top",distance:8,color:"#161917",fontSize:11,fontWeight:700,formatter:({value}:{value:number})=>value.toFixed(1)}}];}
chart.setOption({...common,legend,series});const draw=()=>{const comparisons:BracketComparison[]=[];if(kind==="total")comparisons.push({previousIndex:1,currentIndex:2,previousValue:totals[1],currentValue:totals[2],label:pct(totals[2],totals[1]),level:1,targetGap:26,labelFontSize:8});if(kind==="platform"){const rows=[80,142,204,266];data.platform.series.forEach((item,index)=>{const current=item.values[2],previous=item.values[1],lower=data.platform.series.slice(0,index).reduce((sum,entry)=>sum+entry.values[2],0);comparisons.push({previousIndex:1,currentIndex:2,previousValue:lower+current/2,currentValue:lower+current/2,label:`同比 ${pct(current,previous)}`,variant:"sideLabel",title:item.name,swatchColor:colors[item.name],labelFontSize:8,labelY:rows[index]});});const bilibiliIndex=data.platform.series.findIndex(item=>item.name==="B站");const bilibili=data.platform.series[bilibiliIndex];if(bilibili)bilibili.values.forEach((value,dataIndex)=>{const lowerBoundary=data.platform.series.slice(0,bilibiliIndex).reduce((sum,item)=>sum+item.values[dataIndex],0);comparisons.push({previousIndex:dataIndex,currentIndex:dataIndex,previousValue:lowerBoundary,currentValue:lowerBoundary,label:`${value.toFixed(1)}\n(${(value/totals[dataIndex]*100).toFixed(0)}%)`,variant:"barCallout",color:colors.B站,labelFontSize:8,labelYShift:8,arrowOffset:25})});}setBracketAnnotations(chart,comparisons)};requestAnimationFrame(draw);const ob=new ResizeObserver(()=>{chart.resize();requestAnimationFrame(draw)});ob.observe(ref.current);return()=>{ob.disconnect();chart.dispose()};},[kind]);return <div ref={ref} className="film-chart" role="img" aria-label={kind==="total"?"电影有效播放构成":kind==="coverage"?"B站版权覆盖率":"分平台播放量"}/>}
export function FilmTrend(){const[q,setQ]=useState<QuarterFilter>("Q2");return <section className="horizontal-drama-trend film-trend"><div className="horizontal-drama-lead"><div className="horizontal-drama-subhead"><span>01</span><h4>电影大盘趋势</h4></div><EditableInsight lead="电影播放继续收缩，B站院线新片覆盖提升" body="26Q2 电影有效播放 46.4 亿，同比 -18%；院线电影上新 TOP 50 播放 9.8 亿，同比 -8%。B站覆盖 TOP 50 中的 33 部，覆盖率升至 66%；B站播放 1.1 亿，同比 +10%。" highlights={["46.4 亿","-18%","9.8 亿","-8%","33 部","66%","1.1 亿","+10%"]} storageKey="ogv-market-review:26q2:film-trend-v1"/></div><div className="horizontal-drama-quarter-filter" aria-label="选择季度"><span>显示季度</span>{(["Q1","Q2","Q3","Q4","all"] as const).map(x=><button key={x} type="button" className={q===x?"selected":""} aria-pressed={q===x} onClick={()=>setQ(x)}>{x==="all"?"全部":x}</button>)}</div><div className="film-charts"><article className="horizontal-drama-panel"><header><h5>byQ 电影有效播放（亿）</h5></header><Chart kind="total"/></article><article className="horizontal-drama-panel"><header><div><h5>B站版权覆盖率</h5><span>院线电影上新 TOP 50</span></div></header><Chart kind="coverage"/></article><article className="horizontal-drama-panel"><header><div><h5>byQ 分平台播放（亿）</h5><span>院线电影上新 TOP 50</span></div></header><Chart kind="platform"/></article></div><p className="horizontal-drama-source film-source">数据范围：左图为全部电影有效播放，覆盖存量与增量；右侧两图仅统计院线电影上新 TOP 50。时间范围：2024、2025、2026 年 Q2。数据来源：{data.source}。</p><FilmTop10/></section>}
